-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkaVIgsx3jJItgl/m
pG7HtYXsN+0FVY60OQJJ4JhXEI+gCgYIKoZIzj0DAQehRANCAARNu8GSlD+TMgVf
exNCKHV150ZgOwveDHxZ9rhfpxkS8c45EKkEhzZRlT1Csd7rVit1dPl4iMfnOgcl
9ItYb/Zc
-----END PRIVATE KEY-----